version: '3.8'

services:
  postgres:
    container_name: nestjs-typeorm
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-list
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  # PostgreSQL to tests
  postgres_test:
    container_name: nestjs-typeorm-test
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-list-test
      PGDATA: /data/postgres
    volumes:
      - ./data/pg_test:/data/postgres
